In [6]:
import sys
import os

In [7]:
!{sys.executable} --version

Python 3.6.5 :: Anaconda, Inc.

In [8]:
!{%pip} --version

/bin/sh: {%pip}: command not found

In [9]:
# Import Library for Pyrebase
# install via sudo pip install pyrebase
# install via sudo pip install firebase
import pyrebase as pb

In [10]:
# Extract path of JSON file for Service Account
os.getcwd()

'/Users/rmph/Desktop/Projects - current/Industry'

In [ ]:
# to be included in the config for service account field
!ls *json

In [12]:
# Pyrebase API for Python
# Use service account to authenticate Firebase as Admin and discard security rules
import pyrebase

config = {
  "apiKey": "apikey-here",
  "authDomain": "***.firebaseapp.com",
  "databaseURL": "https://****.firebaseio.com/",
  "storageBucket": "***.appspot.com", # don't include 'gs://'
  "serviceAccount": "/Users/rmph/Desktop/Projects - current/Industry/***.json"
}

firebase = pb.initialize_app(config)

In [13]:
# Authentication
# Create the user (@youremail.com) first in the console
auth = firebase.auth() # authentication service reference
user = auth.sign_in_with_email_and_password("email-here", "password")

In [14]:
utok = user['idToken']

In [15]:
# database service reference
db = firebase.database()

In [16]:
# check user info
uinfo = auth.get_account_info(user['idToken'])

In [17]:
# storage service reference
storage = firebase.storage()

In [18]:
# check storage information
storage.child('/Files')

In [19]:
# Create a pointer to the file in the cloud
storage.child("analyseit-88ed7.appspot.com")

In [21]:
# check path of database file returns storage url
surl = storage.child('/Files').get_url(utok)

In [24]:
surl

'https://firebasestorage.googleapis.com/v0/b/analyseit-88ed7.appspot.com/o/Files?alt=media&token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjY1ZjRhZmFjNjExMjlmMTBjOTk5MTU1ZmE1ODZkZWU2MGE3MTM3MmIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYW5hbHlzZWl0LTg4ZWQ3IiwiYXVkIjoiYW5hbHlzZWl0LTg4ZWQ3IiwiYXV0aF90aW1lIjoxNTQzMDM5NjA0LCJ1c2VyX2lkIjoib3U0bGNHbXpxZVZ3WlZ0S2k1ZlJmTFB1TUZJMiIsInN1YiI6Im91NGxjR216cWVWd1pWdEtpNWZSZkxQdU1GSTIiLCJpYXQiOjE1NDMwMzk2MDQsImV4cCI6MTU0MzA0MzIwNCwiZW1haWwiOiJybXBoZXJyYWR1cmFAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInJtcGhlcnJhZHVyYUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.PDhm4ToqfUFXeX9WlMq8uhtEAJTJponGoFYZ-anP43OF952sM54JBtlI24fnfZYnI3FzP0eGyEEQf839ibaQ7w2kUIiLqdrUqIj4hcml6ougt3PJKZhCASLtg3oHItmyDihnRMYUKzlKTkmu-znXQ_sfcr5jLCHmgjwhYCEOCF2PeUqor_Zn2RreDaMLqGXOHg94OYwAIfT6aLWgx-3PblY4pcIOWnOa84Yo_HH9158C8woijWqaaIjcvMddFJVMMGz0rNug2ojid7Mx36E50JYo4p_h5CzqOm8vGQbP_mHpsFkM4TYh4qIfLBrAiBRBti0eqmcf97rx_K04Iey0Sg'

In [25]:
files

In [26]:
import pandas as pd
import numpy as np

In [27]:
# Directly read data from Firebase Storage
goods = pd.read_table('https://firebasestorage.googleapis.com/v0/b/analyseit-88ed7.appspot.com/o/retail-ms.csv?alt=media&token=460a7c09-768b-4c6c-8d2e-7fb9d8ba49c4')

In [325]:
goods.head()

  Sunday week ending,Actual sausages,saprice,temp,christ,magadst,onlinedis,onlinevid,adshel,tv
0   31/8/14,95.559,-0.226020142,8.4,0,0,2.5,0,0,25.2
1      7/9/14,91.907,-0.195733253,10.2,0,0,2.5,0,0,0
2  14/9/14,95.319,-0.109192335,10.2,0,0,2.5,0,0,90.5
3        21/9/14,86.694,0.101806341,10.2,0,0,0,0,0,0
4       28/9/14,95.548,0.023117832,10.2,0,0,0,0,0,31

In [28]:
# Fix dataframe to fit into columns
pd.read_table('https://firebasestorage.googleapis.com/v0/b/analyseit-88ed7.appspot.com/o/retail-ms.csv?alt=media&token=460a7c09-768b-4c6c-8d2e-7fb9d8ba49c4', sep='\t', delimiter=',')

,Sunday week ending,Actual sausages,saprice,temp,christ,magadst,onlinedis,onlinevid,adshel,tv
0,31/8/14,95.559,-0.226020,8.4,0,0.000000,2.50000,0.0000,0.0,25.2
1,7/9/14,91.907,-0.195733,10.2,0,0.000000,2.50000,0.0000,0.0,0.0
2,14/9/14,95.319,-0.109192,10.2,0,0.000000,2.50000,0.0000,0.0,90.5
3,21/9/14,86.694,0.101806,10.2,0,0.000000,0.00000,0.0000,0.0,0.0
4,28/9/14,95.548,0.023118,10.2,0,0.000000,0.00000,0.0000,0.0,31.0
5,5/10/14,114.724,-0.428181,11.9,0,0.000000,0.00000,0.0000,0.0,17.0
6,12/10/14,109.151,0.267505,11.9,0,0.000000,0.00000,0.0000,0.0,0.0
7,19/10/14,100.360,0.178466,11.9,0,0.000000,0.00000,0.0000,0.0,0.0
8,26/10/14,120.458,0.147908,11.9,0,0.000000,0.00000,0.0000,0.0,0.0
9,2/11/14,117.945,0.273030,13.6,0,0.000000,0.00000,0.0000,0.0,0.0
10,9/11/14,120.466,0.238273,13.6,0,0.000000,0.00000,0.0000,0.0,0.0
11,16/11/14,134.705,-0.600362,13.6,0,0.000000,0.00000,0.0000,0.0,0.0
12,23/11/14,105.649,0.348207,13.6,0,0.000000,13.00000,1.5625,0.0,113.8
13,30/11/14,111.382,0.473684,13.6,0,0.000000,0.00000,1.5625,0.0,44.0
14,7/12/14,124.452,0.433513,15.7,0,0.000000,0.00000,1.5625,0.0,0.0
15,14/12/14,111.478,0.809872,15.7,0,0.000000,0.00000,1.5625,0.0,0.0
16,21/12/14,132.106,0.912845,15.7,1,0.000000,0.00000,0.0000,0.0,0.0
17,28/12/14,160.406,1.264844,15.7,2,0.000000,0.00000,0.0000,0.0,65.2
18,4/1/15,188.279,0.625928,17.1,2,0.000000,0.00000,0.0000,0.0,0.0
19,11/1/15,145.293,0.660209,17.1,1,0.000000,0.00000,0.0000,0.0,33.0
20,18/1/15,172.053,-0.593129,17.1,0,0.000000,0.00000,0.0000,0.0,0.0
21,25/1/15,138.278,0.309878,17.1,0,0.000000,0.00000,0.0000,0.0,33.0
22,1/2/15,129.519,0.351887,17.2,0,0.000000,0.00000,0.0000,0.0,0.0
23,8/2/15,118.429,0.382022,17.2,0,0.000000,0.00000,0.0000,0.0,55.9
24,15/2/15,113.181,0.329902,17.2,0,0.000000,0.00000,0.0000,0.0,0.0
25,22/2/15,101.221,0.654775,17.2,0,0.000000,0.00000,0.0000,0.0,44.1
26,1/3/15,108.746,0.383961,15.5,0,0.000000,0.00000,0.0000,0.0,0.0
27,8/3/15,102.179,0.235664,15.5,0,0.000000,0.00000,0.0000,0.0,44.5
28,15/3/15,104.667,0.283621,15.5,0,0.000000,0.00000,0.0000,0.0,0.0
29,22/3/15,98.075,0.397653,15.5,0,0.000000,0.00000,0.0000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
176,14/1/18,208.854,-0.171763,17.1,0,0.882289,0.00000,0.0000,0.0,18.0
177,21/1/18,183.341,-0.001214,17.1,0,0.873466,0.00000,0.0000,0.0,11.4
178,28/1/18,186.001,0.013471,17.1,1,0.864731,0.00000,0.0000,0.0,23.6
179,4/2/18,170.110,-0.022377,17.2,1,0.856084,0.00000,0.0000,0.0,0.0
180,11/2/18,157.812,0.127700,17.2,0,0.847523,0.00000,0.0000,0.0,70.0
181,18/2/18,151.061,0.216837,17.2,0,0.839048,0.00000,0.0000,0.0,24.9
182,25/2/18,158.824,0.032092,17.2,0,0.830657,0.00000,0.0000,0.0,0.0
183,4/3/18,150.582,0.145799,15.5,0,0.822351,0.00000,0.0000,0.0,31.5
184,11/3/18,150.763,0.118974,15.5,0,0.814127,0.00000,0.0000,0.0,0.0
185,18/3/18,148.272,0.076086,15.5,0,0.805986,0.00000,0.0000,0.0,0.0
186,25/3/18,144.985,0.182768,15.5,0,0.797926,0.00000,0.0000,0.0,0.0
187,1/4/18,163.219,0.252970,12.9,0,0.789947,0.00000,0.0000,0.0,0.0
188,8/4/18,153.372,0.120079,12.9,0,0.782047,0.00000,0.0000,0.0,0.0
189,15/4/18,140.906,0.022105,12.9,0,0.774227,0.00000,0.0000,0.0,0.0
190,22/4/18,156.477,-0.298198,12.9,0,0.766485,0.00000,0.0000,0.0,0.0
191,29/4/18,155.594,-0.504280,12.9,0,0.758820,0.00000,0.0000,0.0,0.0
192,6/5/18,138.554,-0.106360,10.4,0,0.751232,0.00000,0.0000,0.0,0.0
193,13/5/18,130.707,-0.033081,10.4,0,0.743719,0.00000,0.0000,0.0,0.0
194,20/5/18,136.920,-0.071637,10.4,0,0.736282,0.00000,0.0000,0.0,0.0
195,27/5/18,138.945,-0.232086,10.4,0,0.728919,0.00000,0.0000,0.0,0.0
196,3/6/18,139.979,-0.257677,8.1,0,0.721630,1.79488,0.0000,0.0,0.0
197,10/6/18,145.823,-0.346668,8.1,0,0.714414,0.00000,0.0000,0.0,0.0
198,17/6/18,136.807,-0.048742,8.1,0,0.707270,0.00000,0.0000,0.0,0.0
199,24/6/18,136.501,-0.213123,8.1,0,0.700197,0.00000,0.0000,0.0,0.0
200,1/7/18,133.333,-0.009707,7.3,0,0.693195,0.00000,0.0000,0.0,0.0
201,8/7/18,135.807,-0.122820,7.3,0,0.686263,11.89061,0.0000,0.0,0.0
202,15/7/18,135.056,-0.084796,7.3,0,0.679400,0.00000,0.0000,0.0,0.0
203,22/7/18,148.401,-0.534269,7.3,0,0.672606,0.00000,0.0000,0.0,0.0
204,29/7/18,140.935,-0.234425,7.3,0,0.665880,0.00000,0.0000,0.0,0.0
205,5/8/18,148.390,-0.504190,8.4,0,0.659221,8.91796,0.0000,0.0,0.0

In [29]:
goods.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 1 columns):
Sunday week ending,Actual sausages,saprice,temp,christ,magadst,onlinedis,onlinevid,adshel,tv    206 non-null object
dtypes: object(1)
memory usage: 1.7+ KB

In [30]:
surl

'https://firebasestorage.googleapis.com/v0/b/analyseit-88ed7.appspot.com/o/Files?alt=media&token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjY1ZjRhZmFjNjExMjlmMTBjOTk5MTU1ZmE1ODZkZWU2MGE3MTM3MmIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYW5hbHlzZWl0LTg4ZWQ3IiwiYXVkIjoiYW5hbHlzZWl0LTg4ZWQ3IiwiYXV0aF90aW1lIjoxNTQzMDM5NjA0LCJ1c2VyX2lkIjoib3U0bGNHbXpxZVZ3WlZ0S2k1ZlJmTFB1TUZJMiIsInN1YiI6Im91NGxjR216cWVWd1pWdEtpNWZSZkxQdU1GSTIiLCJpYXQiOjE1NDMwMzk2MDQsImV4cCI6MTU0MzA0MzIwNCwiZW1haWwiOiJybXBoZXJyYWR1cmFAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInJtcGhlcnJhZHVyYUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.PDhm4ToqfUFXeX9WlMq8uhtEAJTJponGoFYZ-anP43OF952sM54JBtlI24fnfZYnI3FzP0eGyEEQf839ibaQ7w2kUIiLqdrUqIj4hcml6ougt3PJKZhCASLtg3oHItmyDihnRMYUKzlKTkmu-znXQ_sfcr5jLCHmgjwhYCEOCF2PeUqor_Zn2RreDaMLqGXOHg94OYwAIfT6aLWgx-3PblY4pcIOWnOa84Yo_HH9158C8woijWqaaIjcvMddFJVMMGz0rNug2ojid7Mx36E50JYo4p_h5CzqOm8vGQbP_mHpsFkM4TYh4qIfLBrAiBRBti0eqmcf97rx_K04Iey0Sg'